version: "3"

services: 
    servidor:
        container_name: servicioSocial
        restart: always
        build: .
        ports: 
            - "3000:3000"
        environment: 
            HOST_DB: "192.168.1.6"
            USER_DB: "root"
            PWD_DB: "123"
        