version: "3"

services: 
    base_datos:
        container_name: baseSocial
        build: .
        restart: always
        ports: 
            - "3306:3306"
        environment:
            # Password para el acceso a root
            MYSQL_ROOT_PASSWORD: '123'
            MYSQL_USER: 'admin'
            MYSQL_PASS: '123'
        cap_add:
            - SYS_NICE  # Si se tiene errores ino_db
        command: --default-authentication-plugin=mysql_native_password